services:
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_user
      - db_password
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    secrets:
      - db_user
      - db_password

volumes:
  postgres_data:

secrets:
  db_user:
    file: docker_secrets/db_user.txt
  db_password:
    file: docker_secrets/db_password.txt
